export const actionType = {
    SIGN_IN_SUCCEEDED: "SIGN_IN_SUCCEEDED",
    SIGN_IN_FAILED: "SIGN_IN_FAILED",
    SIGNUP_SUCCEEDED: "SIGNUP_SUCCEEDED",
    SIGNUP_FAILED: "SIGNUP_FAILED",
    GET_POSTS:"GET_POSTS"
}